export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_RUNNING: 'SESSION_ALREADY_RUNNING',
  CONTEXT_RESOLUTION_FAILED: 'CONTEXT_RESOLUTION_FAILED',
  CONTEXT_LOCK_TIMEOUT: 'CONTEXT_LOCK_TIMEOUT',
  CONTEXT_LEASE_EXPIRED: 'CONTEXT_LEASE_EXPIRED',
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  ELEMENT_NOT_FOUND: 'ELEMENT_NOT_FOUND',
  DIALOG_NOT_OPEN: 'DIALOG_NOT_OPEN',
  NETWORK_REQUEST_NOT_FOUND: 'NETWORK_REQUEST_NOT_FOUND',
  TIMEOUT: 'TIMEOUT',
  DAEMON_UNAVAILABLE: 'DAEMON_UNAVAILABLE',
  BROWSER_LAUNCH_FAILED: 'BROWSER_LAUNCH_FAILED',
  CDP_DISCONNECTED: 'CDP_DISCONNECTED',
  IPC_PROTOCOL_ERROR: 'IPC_PROTOCOL_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
